name: API Deploy

on:
  push:
    branches:
      - "main"
    paths:
      - "Api/**"

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Set Tag Version
        run: echo "TAG_VERSION=latest" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./Api
          file: ./Api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tudp-db-manager:${{ env.TAG_VERSION }}
          platforms: linux/amd64, linux/arm64, linux/arm/v7
