name: Webapp deployment

on:
  push:
    branches:
      - "*"
    paths:
      - "WebApp/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Set Tag Version
        id: tag_version
        run: echo "TAG_VERSION=latest" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./WebApp
          file: ./WebApp/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tudp-web-app:${{ env.TAG_VERSION }}
          platforms: linux/amd64, linux/arm64, linux/arm/v7
